name: Package Application with PyInstaller
on:
  push:
    branches:
      - main
      - development
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
        specs: [pyinstaller.spec, nohiddenimports.spec, nodatas.spec, nopathex.spec]  # Specify the PyInstaller spec file if needed
    runs-on: ${{ matrix.os }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pdfminer.six
          pip install pyinstaller  # Install dependencies; modify if using requirements.txt

      - name: Clean previous builds # Remove any previous build artifacts
        shell: bash
        run: rm -rf build dist

      - name: Package Application with PyInstaller
        run: |
          pyinstaller ${{ matrix.specs }}  # Use the specified PyInstaller spec file

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/